server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIS"
  contactDetails:
    name: "Mohamed Ibrahim - Developer"
    email: "mohamed@example.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-12345



